### ISSUE TITLE
Please add license headers using a license approved by OSI and FSF

### ISSUE THREAD

**Issue by hartwork** [mk-fg/pulseaudio-mixer-cli#15]
Hi!

I cannot find license information in the current code base.
Neither in diocumentation nor in the source files that I inspected.
Please add license headers using a license approved by OSI and FSF to all files.
Many thanks!

Best, S

**Comment by mk-fg** [comment]
Thanks for reminder.

I usually commit license file at the start of the repository, but didn't bother here, so forgot all about it.

You did ask for license headers in all files, but I personally don't like making them even more bloated, (and with legalese crap no less), so hope COPYING file in the repo will suffice?

**Comment by hartwork** [comment]
Thanks.
On the every file thing: it is best practice to add it to each file, recommend by the FSF, takes 2 minutes. You may be fine with the single place right now, but it's not ideal. It also advertises little for software libre.
Best, S
