### ISSUE TITLE
Please package using distutils or setuptools

### ISSUE THREAD

**Issue by hartwork** [mk-fg/pulseaudio-mixer-cli#16]
That would allow easy packaging to packagers of Linux distributions.
Thanks in advance.

Best, S

**Comment by mk-fg** [comment]
It's just one script, single file, there's nothing for site-packages, I don't think it should be difficult to install or package.

There are two versions of the thing in the repo though, I don't think both should ever be installed, but adding choice to setup.py would be weird (possible, but no one uses or know about `[tag]` things there afaik).

I think it'll only be more confusing as to what project is (again, one file), add some minor maintenance burden, and might get broken as I won't be using it myself.

Sorry if some particular packaging system makes it difficult to install single executable scripts, but I don't want to add setup.py here.

**Comment by hartwork** [comment]
It's not super hard but currently every distribution has to do the same work, not needed if there was packaging. In addition, adding yourself to to PyPI would become "python setup.py register".
Anyway :)

**Comment by mk-fg** [comment]
Yeah, I have about a dozen modules registered on pypi, but don't feel like it's the right place for executable python scripts that never meant to be imported either.
