### ISSUE TITLE
Unable to autolaunch a dbus-daemon without a $DISPLAY for X11

### ISSUE THREAD

**Issue by mrvanes** [mk-fg/pulseaudio-mixer-cli#17]
When trying to start pulseaudio-mixer-cli from an SSH session to remotely adjust pa-mixer levels just like alsamixer I get the following error: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
My main interreset in pulseaudio-mixer-cli is to be able to remotely adjust pa levels, which seems to be defied by the dependancy to start this dbus daemon?

**Comment by thomasf** [comment]
if you have an x session running on the system you can specify it wh

**Comment by mk-fg** [comment]
Yeah, I think specifying DISPLAY can work for case when dbus gets auto-launched in the X session.
If it gets started from some kind of session-wrapper script or "systemd --user" daemon though, I think dbus socket path should be unrelated to DISPLAY (e.g. tied to systemd session, in the latter case).
`man dbus-launch` describes such things iirc

If your use-case falls under the latter (DISPLAY-independent) category, I think setting DBUS_SESSION_BUS_ADDRESS directly might be a better option, for example (with systemd session):

    export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$USER/bus

**Comment by mk-fg** [comment]
>  My main interreset in pulseaudio-mixer-cli is to be able to remotely adjust pa levels, which seems to be defied by the dependancy to start this dbus daemon?

Re-reading this, realized that maybe your use-case is running pulseaudio without desktop, so you don't have dbus session daemon running at all, same for DISPLAY and such.

Script communicates with pa via dbus only (would be cool if it didn't, but iirc there was no easy lib for pa control protocol), so guess options here are:

* Start dbus daemon with pa daemon.

    I suspect that enabling dbus module in pulse (as mentioned in the README) should already auto-start it, which is fine - just get address from it and use that with the script.

* Script is the wrong tool for the job.

    There's probably other cli tools which might use pulseaudio-specific protocol to talk to it (same as e.g. pacmd).

**Comment by mrvanes** [comment]
I do have a desktop running, but I want to be able to adjust pa volumes from SSH session like I used to be when I used alsa alone. There seems to be no other cli tool for pa that resembles alsamixer.
I'll try to figure out my DISPLAY for the running desktop later.

**Comment by mk-fg** [comment]
Yeah, the DISPLAY or DBUS_SESSION_BUS_ADDRESS should totally work.

One possible hack might be to just grab dbus address from any running pa pid env:

    pid=$(pgrep -xn pulseaudio)\
      && export DBUS_SESSION_BUS_ADDRESS="$(grep -ao -m1 -P '(?<=DBUS_SESSION_BUS_ADDRESS=).*?\0' /proc/"$pid"/environ)"

**Comment by mrvanes** [comment]
Thx, I just tried your hack and it works like a charm!

**Comment by mk-fg** [comment]
Great.
That address might be consistent if same user/DISPLAY is used, so it can be easier to not even bother with grep every time.

**Comment by thomasf** [comment]
yes, for a single user logged in desktop system `DISPLAY` will probably always be `:0`.
