### ISSUE TITLE
log.exception() exits app

### ISSUE THREAD

**Issue by darvelo** [mk-fg/pulseaudio-mixer-cli#18]
For some reason the use of `log.exception()` [here](https://github.com/mk-fg/pulseaudio-mixer-cli/blob/master/pa-mixer-mk3.py#L303) is preventing the app from starting. After some detective work, I've found the error this line produces is `I/O operation on closed file.` I think the "closed file" here is the logger itself. Not sure how to fix it.

**Comment by mk-fg** [comment]
Yeah, not the logger, but stderr stream (so nothing from there would mess with terminal ui).
Which gets closed unless one uses --verbose or --debug option.
Guess either no other logging gets through without --debug, or log.exception is special (as it also formats/dumps backtrace).

Simpliest fix would probably be replacing fd 2 with opened /dev/null.
Thanks for reporting, will fix in a moment.

**Comment by mk-fg** [comment]
Should be fixed in 47f457e5ff3a

**Comment by mk-fg** [comment]
On a separate note - you might want to run the thing as suggested in the [debugging-errors section of the README](https://github.com/mk-fg/pulseaudio-mixer-cli/#debugging-errors) to see what's up with that "Failed to apply stream parameters" error (unless you did already) - probably shouldn't happen, can be a bug or something weird and unexpected in the config.

**Comment by mk-fg** [comment]
> Should be fixed in 47f457e

Realized that script was still closing stderr python object there, 24c6113 should have proper fix.

**Comment by darvelo** [comment]
Thanks for this fix. I'm so used to debugging manually, I didn't realize there was a better way! The reason seems to be, if you follow the example cfg file, that the ConfigParser takes the whole line (including the inline comment) to be the config value.

```
 [stream-sink-hdmi]
 match[alsa.id]: ^HDMI\b
 hidden: true   ; won't be displayed in the list
```

```
 2016-05-26 14:35:26 :: MainThread ERROR :: Failed to apply stream parameters for <PAMixerMenuItem[7fe31435f518] sink[sink-0]: HDMI 0 (hdmi-stereo@snd_hda_int el)>, skipping: <ValueError> true   ; won't be displayed in the list
 Traceback (most recent call last):
   File "./pa-mixer-mk3.py", line 77, in parse_bool
     try: return _states[val.lower()]
 KeyError: "true   ; won't be displayed in the list"
```

**Comment by mk-fg** [comment]
Ah, yeah, apparently this change came in one of python3 releases:

    Changed in version 3.2: In previous versions of configparser behaviour
    matched comment_prefixes=('#',';') and inline_comment_prefixes=(';',).

Trivial to fix by passing that stuff explicitly, ofc, should work as these did before as of ca3f7cd

**Comment by darvelo** [comment]
Thanks! It's fixed. :+1:
