### ISSUE TITLE
cannot connect to pulse because dbus module is not loaded by deafult

### ISSUE THREAD

**Issue by hramrach** [mk-fg/pulseaudio-mixer-cli#19]
updated the code example https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/Clients/DBus/ConnectingToServer/

to work around the issue:
<pre>
#!/usr/bin/env python

import dbus
import os

def connect():
    if 'PULSE_DBUS_SERVER' in os.environ:
        address = os.environ['PULSE_DBUS_SERVER']
    else:
        bus = dbus.SessionBus()
        server_lookup = bus.get_object("org.PulseAudio1", "/org/pulseaudio/server_lookup1")
        address = server_lookup.Get("org.PulseAudio.ServerLookup1", "Address", dbus_interface="org.freedesktop.DBus.Properties")

    return dbus.connection.Connection(address)

try:
        conn = connect()
        core = conn.get_object(object_path="/org/pulseaudio/core1")
except dbus.exceptions.DBusException as e:
        if e.get_dbus_name() == 'org.freedesktop.DBus.Error.FileNotFound':
          os.system("sh -x -c ' pactl list modules short | grep -q dbus || pactl load-module module-dbus-protocol'")
          conn = connect()
          core = conn.get_object(object_path="/org/pulseaudio/core1")
        else:
          raise e

print "Successfully connected to " + core.Get("org.PulseAudio.Core1", "Name", dbus_interface="org.freedesktop.DBus.Properties") + " " + core.Get("org.PulseAudio.Core1", "Version", dbus_interface="org.freedesktop.DBus.Properties") + " !"
</pre>

**Comment by mk-fg** [comment]
Yeah, guess pactl can be used to load dbus module, but I'd rather not do it in the script - just enable it via default.pa file or whatever other method.
I think README also mentions that old scripts need the thing too.

On a mostly-unrelated note: maybe use pa-mixer-mk3.py instead - it doesn't need/use dbus at all.

**Comment by hramrach** [comment]
Except the default.pa is global and while you can make a user copy I am not sure how it interacts in case the global gets updated. In other words it is also messy in another way. Maybe you could ask the user before loading the module or something.

And the default python is 2.7 on my distro which is why the v2 works for me.

Anyway, I was researching this because I wanted to connect to pulsaudio with my script. Getting the terminal mixer working is a nice bonus so I am sharing the script in case other users of the mixer find it useful.

**Comment by mk-fg** [comment]
You're right, I'm probably just too used to running pulse with custom startup script, which is unlikely to be the norm or even known.
Will add as a default to dbus scripts.
Thanks for the explaination, I think it's indeed a good idea.

**Comment by mk-fg** [comment]
Should be fixed in d040c44
