### ISSUE TITLE
unable to start pulse

### ISSUE THREAD

**Issue by sherifomran** [mk-fg/pulseaudio-mixer-cli#20]
i am trying it on raspberry pi for narrowed system with systemv.
when i start pulseaudio, i get it cannot run in system mode.  autospawn is disabled and i don't see much difference when enabling it.  I get also unable to autolaunch a dbus-daemon without a $DISPLAY for X11. I don't have x11.

**Comment by mk-fg** [comment]
Sure.
Why'd you ask about it here then? It's not a pulseaudio support forum of any kind.
Also, even if it was, there's not even remotely enough information to tell anything from that one-liner issue description.
